name: nagl2-conf-gen
channels:
  - conda-forge
  - openeye
dependencies:
  - python
  - pip
  - click
  - openff-toolkit
  - openff-qcsubmit
  - openmmforcefields
  - openeye::openeye-toolkits
  - openff-interchange-base
  - qcportal
  - geometric=1
  - jupyter
  - seaborn
  - pandas
  - pydantic =2
  - ipython
  - ipdb
  - pre-commit
  - rich
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly
  - pytest-timeout
  - smirnoff-plugins
  - click-option-group
  - dask
  - dask-jobqueue
  - tqdm
  - openmm
  - ambertools
  - qubekit
  - forcebalance=1.9.6
  - ndcctools
  - cmiles
  - geometric
  - black
  - isort
  - flake8 
  - mamba
  - nglview
  - multiprocess
  - mamba=2.0.2 
