name: qca-clean-openff
channels:
  - conda-forge
  - openeye
dependencies:
  - python=3.11
  - numpy
  - jupyter
  - periodictable
  - qcportal>=0.61
  - qcfractal>=0.61
  - qcfractalcompute>=0.61
  - openff-qcsubmit
  - openff-toolkit
  - openeye-toolkits