name = "OpenFF Sulfur Hessian Training Coverage Supplement v1.1"
description = """

A basic data set created to improve the training coverage of sulfonic and
phosphonic acids, sulfone, sulfonate, sulfinyl, sulfoximine, sulfonamides,
thioether, and 1,3-thiazole groups. The structures in this data set are the
optimized geometries from `OpenFF Sulfur Optimization Training Coverage
Supplement v1.0`.

"""
short_description = "Additional Hessian training data for Sage sulfur and phosphorus parameters"
class = "optimization"
purpose = "Improve coverage in Sage"
submitter = "Brent Westbrook"

[[pipeline]]
filename = "generate-dataset.py"
description = "This script shows how the dataset was prepared."

# input files
[[manifest]]
filename = "generate-dataset.py"
description = "Script describing dataset generation and submission"

[[manifest]]
filename = "input-environment.yaml"
description = "Environment file used to create the Python environment for the script"

[[manifest]]
filename = "full-environment.yaml"
description = "Fully-resolved environment used to execute the script"

[[manifest]]
filename = "opt.toml"
description = """
Experimental [qcaide](https://github.com/ntBre/qcaide) input file for defining
variables used throughout the QCA submission process
"""

# output files
[[manifest]]
filename = "dataset.json.bz2"
description = "Compressed dataset ready for submission"

[[manifest]]
filename = "dataset.pdf"
description = "Visualization of dataset molecules"

[[manifest]]
filename = "dataset.smi"
description = "SMILES strings for dataset molecules"