name: qcsub_env
channels:
  - conda-forge
  - omnia
  - openeye
  - defaults
  - omnia/label/rc
dependencies:
  - cmiles
  - openforcefield
  - qcfractal
  - qcsubmit=v0.1.0
  - openeye-toolkits
  - basis_set_exchange

