name = "OpenFF Lipid Optimization Training Supplement v1.0"
description = """

An optimization data set created to improve the training coverage of lipid-like
molecules in Sage. The molecules in this data set were selected from the [LIPID
MAPS](https://www.lipidmaps.org/) database via
[cura](https://github.com/ntBre/curato/tree/6039bea5c64f8cd6b374fd12b5fa3b355898d98b)
after being fragmented by the [XFF
fragmentation](https://github.com/XtalPi-XFF/2023_XFF_paper/tree/b84ef6079d24ebd2e86f78a495e3257b375255fa/fragmentation)
algorithm, clustered on the 2048-bit, radius-3 Morgan fingerprint from RDKit by
the `LeaderPicker.LazyBitVectorPick` algorithm, also from RDKit, with a distance
threshold of 0.6559. Placeholder dummy atoms in the fragments were generally
filled with H atoms, and `S(=O)(=O)*` groups were replaced with `S(=O)([O-])`.
The candidate fragments were further restricted to those with between 3 and 70
heavy atoms and containing only the elements Cl, P, Br, I, H, C, O, N, F, and S.
Candidates with InChIKeys matching existing Sage training or benchmarking data
were also filtered out.

"""
short_description = "Additional optimization training data for Sage from representative LIPID MAPS fragments"
class = "optimization"
purpose = "Improve training coverage in Sage"
submitter = "Brent Westbrook"

[[pipeline]]
filename = "generate-dataset.py"
description = """
This script shows how the dataset was prepared from the input file `input.smi`.
"""

[[pipeline]]
filename = "main.py"
description = """
This script shows how the dataset was prepared from the initial cura database.
"""

# input files
[[manifest]]
filename = "generate-dataset.py"
description = "Script describing dataset generation and submission"

[[manifest]]
filename = "input-environment.yaml"
description = "Environment file used to create the Python environment for the script"

[[manifest]]
filename = "full-environment.yaml"
description = "Fully-resolved environment used to execute the script"

[[manifest]]
filename = "opt.toml"
description = """
Experimental [qcaide](https://github.com/ntBre/qcaide) input file for defining
variables used throughout the QCA submission process
"""

# output files
[[manifest]]
filename = "dataset.json.bz2"
description = "Compressed dataset ready for submission"

[[manifest]]
filename = "dataset.pdf"
description = "Visualization of dataset molecules"

[[manifest]]
filename = "output.smi"
description = "SMILES strings for dataset molecules"