name: submit-hess-ds
channels:
  - conda-forge
  - openeye
dependencies:
  - python
  - openff-toolkit
  - openff-qcsubmit
  - openmmforcefields
  - openeye::openeye-toolkits
  - openff-interchange-base
  - qcportal
  - jupyter
  - ipython
  - ipdb
  - smirnoff-plugins
  - tqdm
  - cmiles
  - mamba
  - nglview
