name = "OpenFF Torsion Multiplicity Optimization Benchmarking Coverage Supplement v1.0"
description = """

An optimization data set created to improve the benchmarking coverage of both
existing Sage 2.2.0 proper torsion parameters and new parameters added through
the torsion multiplicity project. The molecules in this data set were partly
selected from the ChEMBL 33 database and partly generated manually to match
parameters not covered by ChEMBL.

"""
short_description = "Additional optimization benchmarking data for Sage 2.2.0 proper torsions and new parameters from the torsion multiplicity work"
class = "optimization"
purpose = "Improver proper torsion coverage in Sage"
submitter = "Brent Westbrook"

[[pipeline]]
filename = "generate-dataset.py"
description = """
This script shows how the dataset was prepared from the input files:
`bench.opt.smi` and `ff.offxml`.
"""

[[pipeline]]
description = """
The list of proper torsion parameter ID and SMILES pairs in `bench.opt.smi` were
collected by searching the ChEMBL database for all of the molecules matching the
parameters of interest. The code used for all of these steps can be found
[here](https://github.com/ntBre/valence-fitting/tree/c1e98fb20e7a4c9622ff031d8b23fb0b1846be7d/02_curate-data/frag).
"""

# input files
[[manifest]]
filename = "generate-dataset.py"
description = "Script describing dataset generation and submission"

[[manifest]]
filename = "input-environment.yaml"
description = "Environment file used to create Python environment for the script"

[[manifest]]
filename = "full-environment.yaml"
description = "Fully-resolved environment used to execute the script"

[[manifest]]
filename = "ff.offxml"
description = "Draft force field with Sage 2.2.0 proper torsions split to ensure single multiplicities"

[[manifest]]
filename = "opt.toml"
description = "Experimental input file for defining variables used throughout the QCA submission process"

# output files
[[manifest]]
filename = "dataset.json.bz2"
description = "Compressed dataset ready for submission"

[[manifest]]
filename = "dataset.pdf"
description = "Visualization of dataset molecules"

[[manifest]]
filename = "dataset.smi"
description = "Smiles strings for dataset molecules"