name: qcarchive-user-submit

channels:
  - conda-forge
  - openeye

dependencies:
  - python =3.11
  - pip
  - qcportal >=0.49
  - openff-qcsubmit
  - openff-toolkit
  - openeye-toolkits
  - click
  - pip:
    - git+https://github.com/ntBre/qcaide
    - git+https://github.com/ntBre/curato
