name = "OpenFF Torsion Multiplicity Optimization Training Coverage Supplement v1.0"
description = """

An optimization data set created to improve the coverage of both existing Sage
2.2.0 proper torsion parameters and new parameters added through the torsion
multiplicity project. The molecules in this data set were partly selected from
the ChEMBL 33 database and partly generated manually to match parameters not
covered by ChEMBL.

"""
short_description = "Additional optimization training data for Sage 2.2.0 proper torsions and new parameters from the torsion multiplicity work"
class = "optimization"
purpose = "Improver proper torsion coverage in Sage"
submitter = "Brent Westbrook"

[[pipeline]]
filename = "generate-dataset.ipynb"
description = """
This notebook shows how the dataset was prepared from the input files:
`train.opt.smi` and `ff.offxml`.
"""

[[pipeline]]
description = """
The list of proper torsion parameter ID and SMILES pairs in `train.opt.smi` were
collected by searching the ChEMBL database for all of the molecules matching the
parameters of interest. The code used for all of these steps can be found
[here](https://github.com/ntBre/valence-fitting/tree/c1e98fb20e7a4c9622ff031d8b23fb0b1846be7d/02_curate-data/frag).
"""

[[manifest]]
filename = "dataset.json.bz2"
description = "Compressed dataset ready for submission"

[[manifest]]
filename = "dataset.pdf"
description = "Visualization of dataset molecules"

[[manifest]]
filename = "dataset.smi"
description = "Smiles strings for dataset molecules"

[[manifest]]
filename = "generate-dataset.ipynb"
description = "Notebook describing dataset generation and submission"

[[manifest]]
filename = "input-environment.yaml"
description = "Environment file used to create Python environment for the notebook"

[[manifest]]
filename = "full-environment.yaml"
description = "Fully-resolved environment used to execute the notebook"
