name = "OpenFF Sulfur Optimization Training Coverage Supplement v1.0"
description = """

An optimization data set created to improve the training coverage of sulfonic
and phosphonic acids, sulfone, sulfonate, sulfinyl, sulfoximine, sulfonamides,
thioether, and 1,3-thiazole groups. The molecules in this data set were selected
from the ChEMBL 34 database.

"""
short_description = "Additional optimization training data for Sage sulfur and phosphorus parameters"
class = "optimization"
purpose = "Improve coverage in Sage"
submitter = "Brent Westbrook"

[[pipeline]]
filename = "generate-dataset.py"
description = """
This script shows how the dataset was prepared from the input files: `train.smi`
and `ff.offxml`.
"""

[[pipeline]]
description = """
The list of labels and SMILES pairs in `train.smi` were collected by searching
the ChEMBL database for all of the molecules matching the SMIRKS patterns
corresponding to the labels in `sulfur.dat`. The code used for all of these
steps can be found
[here](https://github.com/ntBre/curato/tree/64261e2261e5b3109223c7fbe8ef5d866937fd13).
"""

# input files
[[manifest]]
filename = "generate-dataset.py"
description = "Script describing dataset generation and submission"

[[manifest]]
filename = "input-environment.yaml"
description = "Environment file used to create the Python environment for the script"

[[manifest]]
filename = "full-environment.yaml"
description = "Fully-resolved environment used to execute the script"

[[manifest]]
filename = "ff.offxml"
description = "Draft force field with Sage 2.2.0 proper torsions split to ensure single multiplicities"

[[manifest]]
filename = "opt.toml"
description = """
Experimental [qcaide](https://github.com/ntBre/qcaide) input file for defining
variables used throughout the QCA submission process
"""

# output files
[[manifest]]
filename = "dataset.json.bz2"
description = "Compressed dataset ready for submission"

[[manifest]]
filename = "dataset.pdf"
description = "Visualization of dataset molecules"

[[manifest]]
filename = "dataset.smi"
description = "SMILES strings for dataset molecules"