---
# lifecycle processing for all datasets currently being tracked - error cycling

name: "Dataset Lifecycle - Reprioritize/Retag"

on:
  # run five times a day
  schedule:
    - cron: "0 00,04,08,16,20 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  exec-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: ensure we only have one instance running
        uses: softprops/turnstyle@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DANGERBOT_TOKEN_LIMITED }}
        with:
          abort-after-seconds: 60

      - name: Additional info about the build
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/error-cycle.yaml
          create-args: >-
            python=3.11
          cache-environment: true

      - name: Environment Information
        run: |
          conda info
          conda list

      - name: Run lifecycle processing script
        env:
          GH_TOKEN: ${{ secrets.GH_DANGERBOT_TOKEN_LIMITED }}
          QCA_USER: ${{ secrets.QCA_USER }}
          QCA_KEY: ${{ secrets.QCA_KEY }}
        run: |
            python ./management/lifecycle.py --states "Error Cycling" --set-priority --set-computetag
