---
# test lifecycle processing

name: Test lifecycle

on:
  pull_request:
    branches:
      - master
    types:
      - labeled
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-lifecycle:
    if: contains(github.event.pull_request.labels.*.name, 'test-ci')
    runs-on: ubuntu-latest
    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: ensure we only have one instance running
        uses: softprops/turnstyle@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DANGERBOT_TOKEN_LIMITED }}
        with:
          abort-after-seconds: 60

      - name: Additional info about the build
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/queued-submit.yaml
          create-args: >-
            python=3.11
          cache-environment: true

      - name: Environment Information
        run: |
          conda info
          conda list

      - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
        env:
          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
        run: |
          echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}

      - name: Run lifecycle processing script
        env:
          GH_TOKEN: ${{ secrets.QCA_DATASET_SUBMISSION_PAT }}
          QCA_USER: ${{ secrets.QCA_USER }}
          QCA_KEY: ${{ secrets.QCA_KEY }}
        run: |
            python ./management/lifecycle-v2.py --run-tests
