name = "OpenFF Torsion Multiplicity Torsion Drive Coverage Supplement v1.0"
description = """

A torsion drive data set created to improve the coverage of both existing Sage
2.2.0 proper torsion parameters and new parameters added through the torsion
multiplicity project. The molecules in this data set were partly selected from
the ChEMBL 33 database and partly generated manually to match parameters not
covered by ChEMBL.

"""
short_description = "Additional torsion drive training data for Sage 2.2.0 proper torsions and new parameters from the torsion multiplicity work"
class = "torsiondrive"
purpose = "Improver proper torsion coverage in Sage"
submitter = "Brent Westbrook"

[[pipeline]]
filename = "generate-dataset.ipynb"
description = "This notebook shows how the dataset was prepared from the input files: `all.smiles` and `tm.v2.offxml`."

[[pipeline]]
description = """
The list of proper torsion parameter ID and SMILES pairs in all.smiles were
collected by searching the ChEMBL database for all of the molecules matching the
parameters of interest, fragmenting these molecules with the RECAP algorithm as
implemented in RDKit, clustering them based on their 1024-bit Morgan
fingerprints using the DBSCAN algorithm, and taking the two smallest molecules
from these cluster centroids. The code used for all of these steps can be found
here.
"""

# this would be nicer as an inline table (manifest = [ {filename = , desc = },
# ... ]) but the python lib seems unable to parse this if it contains newlines.
# putting it all on one line is probably more annoying than this
[[manifest]]
filename = "dataset.json.bz2"
description = "Compressed dataset ready for submission"

[[manifest]]
filename = "dataset.pdf"
description = "Visualization of dataset molecules"

[[manifest]]
filename = "dataset.smi"
description = "Smiles strings for dataset molecules"

[[manifest]]
filename = "generate-dataset.ipynb"
description = "Notebook describing dataset generation and submission"

[[manifest]]
filename = "input-environment.yaml"
description = "Environment file used to create Python environment for the notebook"

[[manifest]]
filename = "full-environment.yaml"
description = "Fully-resolved environment used to execute the notebook"